Dawn/network protos
pioneers/PieCentral pull request #111
Opened 2017-02-05 01:04 UTC by jhuang99

Fixed proto definition to make the header an enum.

2017-02-05 05:41 UTC, kevinmasd submitted a review, later dismissed
Seems to have a merge conflict. Also, has runtime been notified of these changes?

2017-02-05 19:27 UTC, yizow requested changes
Style

2017-02-05 19:27 UTC, yizow commented on ansible-protos/notification.proto
> +}
Newline at end of file

2017-02-08 08:29 UTC, jhuang99 commented on ansible-protos/notification.proto
> +}
Fixed

2017-02-08 08:30 UTC, jhuang99 commented
Talked to @bodiddles about the change and fixed merge conflict.

2017-02-09 04:36 UTC, yizow approved these changes

2017-02-09 04:37 UTC, merged