[HIBIKE] update firmware library to new protocol and implement example device
pioneers/PieCentral pull request #112
Opened 2017-02-05 01:07 UTC by karthik-shanmugam

- Implement parsing and constructing for new packet types in hibike/lib/hibike_message.cpp
- Implement new protocol behavior in hibike/lib/hibike_device.cpp
- Update ExampleDevice firmware to use updated hibike library api

2017-02-05 02:01 UTC, nikitakit requested changes
This PR is very clean and does only one thing. Thanks for splitting things up, it's been a pleasure to review!

I have a few stylistic comments, but so far nothing major stood out to me (though I may notice some more things when I take a second look a little later)

2017-02-05 02:01 UTC, nikitakit commented on hibike/devices/ExampleDevice/example_device.cpp
> +uint8_t device_data_update(uint8_t param, uint8_t* data_update_buf, size_t buf_len) {
Do note that neither `device_data_update` nor `device_write` do any bounds checking based on the buffer length argument. This need not block merging, but I don't think its right to document that bounds checking must happen and then not do it. At least a TODO somewhere would be nice.

But if correct bounds checking is needed during the course of normal operation (and not just debugging), then it should absolutely be implemented here.

2017-02-05 02:01 UTC, nikitakit commented on hibike/devices/ExampleDevice/example_device.h
> +#define NUM_PARAMS 6 //change to however many params are needed
Where is `NUM_PARAMS` used? Based on the current diff it looks deprecated, in which case you should consider removing it.

2017-02-05 02:01 UTC, nikitakit commented on hibike/devices/ExampleDevice/example_device.h
> +} param;
For style reasons, the name `param` should not be all lowercase. I think better style would be `Param`.

2017-02-05 02:01 UTC, nikitakit commented on hibike/devices/ExampleDevice/example_device.cpp
> +    case VALUE_0:
I wonder if it would be better to namespace the enum when using it, e.g. `Param::VALUE_0`.

2017-02-05 02:01 UTC, nikitakit commented on hibike/devices/ExampleDevice/example_device.cpp
> +  switch (param) {
If you're using an enum type, I think you should cast the variable `param` to the enum. IIRC switching on an enum value will warn if there are any values of the enum that are not handled, but I'm not sure if switching on a uint8_t will do that. (Fix would be something like `switch ((ParamEnum)param)`, or similar but using `static_cast`).

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +// uint8_t param;
Delete instead of commenting out.

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +          // param = hibikeBuff.payload[0] - 1;
delete instead of commenting out.

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +        // case DESCRIPTION_REQUEST:
delete instead of commenting out. Add a TODO if this feature will ever need to be re-implemented.

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +  // if ((subDelay > 0) && (currTime - prevTime >= subDelay)) {
Delete instead of commenting out. Add TODO if this functionality will need to be re-enabled later.

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_message.cpp
> +//deprecated but not really
Uh... what is this comment supposed to mean?

If this is not actually deprecated, the comment should be more descriptive. If it is, why is the code still here?

If this not being deleted yet has to do with the order you're submitting PRs, then let me know (odd intermediate states is a normal occurrence, and usually isn't a problem)

2017-02-05 02:01 UTC, nikitakit commented on hibike/lib/hibike/hibike_message.cpp
> +          params &= ~(1<<count);
This else condition look like a no-op. Should it be deleted?

2017-02-09 01:10 UTC, karthik-shanmugam commented on hibike/lib/hibike/hibike_message.cpp
> +          params &= ~(1<<count);
It's supposed to unset the corresponding bit of `params` to indicate that a value for that param is not contained within the packet. The else clause will occur if `device_data_update()` writes nothing to the buffer for a specific param, possibly due to insufficient buffer space or an invalid param.

2017-02-09 01:18 UTC, karthik-shanmugam commented on hibike/lib/hibike/hibike_device.h
> +extern uint8_t device_data_update(uint8_t param, uint8_t* data_update_buf, size_t buf_len);
I think this should be renamed to `device_read()` and have the same argument names as `device_write()` to make things cleaner. This change would be need to be made in multiple places:
 - The hibike firmware library
 - Firmware for each specific device
 - DEVELOPERS.md

2017-02-09 02:42 UTC, karthik-shanmugam commented on hibike/devices/ExampleDevice/example_device.cpp
> +uint8_t device_data_update(uint8_t param, uint8_t* data_update_buf, size_t buf_len) {
resolved by adding bounds checking

2017-02-09 03:31 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +          // params = hibikeBuff.payload[0] - 1;
Commented out code should be removed

2017-02-09 03:32 UTC, nikitakit commented on hibike/lib/hibike/hibike_message.cpp
> +          params &= ~(1<<count);
You're right. I must have been asleep when reading the code last time.

2017-02-11 06:13 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +          // params = hibikeBuff.payload[0] - 1;
FYI I looked over your latest changes, and this comment is currently the only non-ideal thing in the code that I've found.

2017-02-15 02:59 UTC, nikitakit approved these changes
Good catch on the payload length calculation changes!

This code now LGTM, and I think any remaining bugs can be addressed in future PRs.

(Sorry for late reply. FYI when you pushed the last commit to the PR I don't remember getting notified, probably because github notifies on comments but not on commits)

2017-02-16 03:33 UTC, merged