Devops/deployment
pioneers/PieCentral pull request #130
Opened 2017-02-16 04:07 UTC by ArjunSridhar1

Various bug fixes and added a networking config script.
Changes:
 - Removed conman, and added kernel updating to install scripts (may need to be reverted)
 - Added protobuf compiler to update script
 - Created network config script
 - Added Arduino micro udev rules

2017-02-16 04:59 UTC, nikitakit commented
FYI I've moved all of your changes to `create_update.sh` into my branch (see #131)

2017-02-18 23:31 UTC, yizow reviewed
Sanity checked changes; deferring approval to someone with more specific systems knowledge.
otherwise lgtm

2017-02-18 23:31 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +#connmanctl services
we can just delete these lines instead of commenting.

2017-02-18 23:31 UTC, yizow commented on DevOps/frankfurter/resources/interfaces.py
> +def write_tmp_file(lines):
for future reference, consider:
https://docs.python.org/3.5/library/tempfile.html

2017-03-04 09:57 UTC, nikitakit commented
When this PR was opened, it appeared to me that the code was not yet complete (as evidenced by the large number of commits done afterward). Is it now in a state where it can be merged?

It would be ideal that the deployment scripts used for kickoff come from the master branch, rather than remaining unmerged.

2017-03-05 05:25 UTC, jonathan-j-lee commented
We are now waiting on: 
1. configuration in `interfaces` for interacting with the field control router, and
2. updating on boot (updating from Dawn should still work).

2017-03-07 03:29 UTC, brandonxxlee commented
Just checking, the sensor mapping is also preserved right after runtime update. (This feature isn't currently working in Dawn, but this file should also persist through updates)

2017-03-07 03:42 UTC, ArjunSridhar1 commented
@brandonxxlee We only preserve studentCode.py. What other files do you need to preserve? Would it be better to put files that need to be preserved into a separate folder? If it's only 2 files, we could just replace those manually.

2017-03-07 03:55 UTC, yizow commented
namedPeripherals.csv also needs to be preserved
it stores student code name - uid mappings.

2017-03-10 01:23 UTC, yizow requested changes

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/README.md
> +3. Student code should be kept in a separate directory at `/home/ubuntu/studentcode`.
is this still valid?

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +    #script /home/ubuntu/whichwifi.sh
remove this comment

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +#or switch to static
this comment seems out of place
convention is: comment applies to following line

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +    wpa-ssid "router_name"
is this correct? is it set from the ra0 mapping above?

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +    map student
doesn't map take two arguments?

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces
> +    wpa-ssid "router_name"
Ah i see the python file sets it
Please add a comment in here
`x, y, z are set in {scripy}.py`

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/interfaces.py
> +    main()
add newline at end of file

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/resources/update.sh
> +rm -f $UPDATES_DIR/*.tar.gz && rm -rf $UPDATES_DIR/tmp
newline at end of file

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/scripts/install/master_frank_setup.sh
>  mkdir -p $HOME/studentcode
is this still needed?

2017-03-10 01:23 UTC, yizow commented on DevOps/frankfurter/scripts/install/master_frank_setup.sh
> +# Aliases for runtime development
If this is here, it shouldn't be hardcoded in the bashrc file
Choose one or the othe

2017-03-11 00:22 UTC, yizow approved these changes

2017-03-11 00:24 UTC, merged