[DAWN] webpack: Use ES6 and simplify config
pioneers/PieCentral pull request #143
Opened 2017-02-19 02:01 UTC by mc10

This also removes the redundant production file by combining them into one file.

2017-02-20 21:08 UTC, kevinmasd requested changes
I would leave off handling Webpack. This can be done later when we can upgrade from Webpack 1 to 2.

2017-02-20 21:08 UTC, kevinmasd commented on dawn/webpack.production.config.js
> -      'NODE_ENV': '"production"'
We keep a production variable to differentiate what is being developed vs what should be shipped to students

2017-02-20 21:12 UTC, kevinmasd commented on dawn/webpack.production.config.js
> -      'NODE_ENV': '"production"'
Actually, after seeing package.json, I'll get back to you on this.

2017-02-20 21:54 UTC, mc10 commented
I don't think I've changed any of the code of the webpack file, just ES6-ifyed it. Updating to Webpack 2.0 shouldn't really be affected imo.

2017-03-02 07:58 UTC, mc10 commented
@kevinmasd I think this is mergeable without worrying about Webpack 2.0; you should be able to make that upgrade right on top of these changes.

2017-03-05 08:46 UTC, kevinmasd requested changes

2017-03-05 08:46 UTC, kevinmasd commented on dawn/webpack.config.babel.js
> +const target = process.env.NODE_ENV === 'production' ? 'electron' : 'atom';
This was a mistake in the originals; we should probably default to electron.

2017-03-05 08:49 UTC, mc10 commented on dawn/webpack.config.babel.js
> +const target = process.env.NODE_ENV === 'production' ? 'electron' : 'atom';
So should this always be `'electron'`?

2017-03-05 09:05 UTC, kevinmasd commented on dawn/webpack.config.babel.js
> +const target = process.env.NODE_ENV === 'production' ? 'electron' : 'atom';
Yes

2017-03-05 09:08 UTC, kevinji commented on dawn/webpack.config.babel.js
> +const target = process.env.NODE_ENV === 'production' ? 'electron' : 'atom';
Fixed in latest commit.

2017-03-05 09:24 UTC, kevinmasd approved these changes

2017-03-05 09:24 UTC, merged