[HIBIKE] TeamFlag firmware
pioneers/PieCentral pull request #148
Opened 2017-02-23 04:11 UTC by karthik-shanmugam

Hopefully this is a pretty straightforward pull request.

Team flag firmware is now basically just 6 individually controllable LEDs. It doesn't support any of the modes that last years' firmware had; it now relies on runtime to implement all of its behavior. This can be changed if this is an issue.

2017-02-23 05:06 UTC, nikitakit requested changes
The changes here actually LGTM.

Sad to see the special on-boot blinking mode go, but I understand that it's non-critical.

You need to also update `hibikedevices.json`, though.

2017-02-23 05:30 UTC, karthik-shanmugam commented
The only change to make in the json file would be removing the mode parameter right? It might be better to leave that in there even though it's not implemented for now; it makes it easier to implement it later and makes it more understandable as to why the TeamFlag's parameters start at 1 instead of 0

2017-02-23 05:33 UTC, nikitakit requested changes
Oh I see, I actually missed that the params don't start at zero.

Could you make a TODO comment in the code, and also make sure that accidental reads/writes to the value don't cause unrecoverable errors for either the firmware or the python side?

2017-02-23 05:33 UTC, nikitakit commented on hibike/devices/TeamFlag/team_flag.h
> +#define PARAM_BLUE 1
Add comment here about param 0

2017-02-25 09:07 UTC, yizow requested changes
Minor style.

Though, i'm curious why the .json file was removed. I wasn't aware hibike had any architecture changes; doesn't it still need that file? 

Double check pinout

2017-02-25 09:07 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.cpp
>  }
newline at end of file

2017-02-28 07:52 UTC, karthik-shanmugam commented on hibike/devices/TeamFlag/team_flag.cpp
>  }
There's just one json file in the hibike folder for all the devices now

2017-02-28 07:59 UTC, nikitakit approved these changes

2017-03-02 00:52 UTC, yizow approved these changes

2017-03-02 03:34 UTC, merged