[RUNTIME] Send Sensors to Dawn
pioneers/PieCentral pull request #159
Opened 2017-02-26 00:19 UTC by brandonxxlee

Reformatted sending to accurately read SM to send sensors to dawn.

2017-02-26 04:23 UTC, nikitakit submitted a review, later dismissed
see comments

2017-02-26 04:23 UTC, nikitakit commented on ansible-protos/runtime.proto
> +        repeated ParamValue param_value = 6;
How will we handle non-float-valued params?

One possibility is to later modify ParamValue to instead be:
```
string param = 1;
oneof kind {
    float float_value = 2;
    int int_value = 3
}
```

If that is the eventual plan, then it may make sense to name the field `float_value` to facilitate this eventual transition.

2017-02-26 04:23 UTC, nikitakit commented on runtime/testy/runtimeUtil.py
> +  IDLE = 2
So these are out of order and don't start at zero. Could you explain why that is?

(If you're just matching the protobuf, then you should import these values from `runtime_pb2`)

2017-02-27 23:48 UTC, brandonxxlee commented on ansible-protos/runtime.proto
> +        repeated ParamValue param_value = 6;
Changed proto to include oneof so that can in future support different data types.

2017-02-28 02:26 UTC, nikitakit requested changes
I suspect the compiled protos in this PR have not been updated.

2017-02-28 02:38 UTC, yizow approved these changes
lgtm

2017-02-28 02:43 UTC, nikitakit approved these changes
lgtm

2017-02-28 04:36 UTC, merged