[RUNTIME] Allows Dawn to reconnect to the robot
pioneers/PieCentral pull request #168
Opened 2017-02-28 08:24 UTC by bodiddles

Fixes #140 by killing all Ansible processes and studentCode if Dawn disconnects and resets UDP Recv to allow for a new Dawn connection. 

Also fixes bug where killing studentCode process would leave it alive and cause runtime to kill with os.kill and end the runtime process. Made the while loop calling the function for running studentCode check if the terminated flag is true.

2017-02-28 08:35 UTC, yizow requested changes

2017-02-28 08:35 UTC, yizow commented on runtime/testy/Ansible.py
> -
why delete this line?

2017-02-28 08:35 UTC, yizow commented on runtime/testy/Ansible.py
> +        from_pipe = pipe.recv()
why make this change?

2017-02-28 08:35 UTC, yizow commented on runtime/testy/Ansible.py
> -
why delete this line

2017-02-28 08:35 UTC, yizow commented on runtime/testy/Ansible.py
> +                if recv_data == b'':
no timeout? what if we drop a connection for a few milliseconds?

2017-02-28 08:35 UTC, yizow commented on runtime/testy/Ansible.py
> +                if recv_data == b'':
also, this is tcp. when would we ever receive an empty tcp packet?

2017-02-28 08:35 UTC, yizow commented on runtime/testy/stateManager.py
> +      SM_COMMANDS.ENTER_AUTO: self.enter_auto,
I thought commas at the end like this broke things?

2017-02-28 08:37 UTC, bodiddles commented on runtime/testy/Ansible.py
> +                if recv_data == b'':
timeout should be included in the socket itself. When it returns an empty byte string, it indicates that the socket on the other end has closed so in this case, we would want to actually restart all ansible processes

2017-02-28 08:48 UTC, yizow approved these changes
lgtm

2017-02-28 09:29 UTC, nikitakit commented
I see a failing `hibikeSubscribeDevice` on one of the two travis runs. Is it possible that this flaky tests points to some underlying problem?

2017-02-28 09:42 UTC, nikitakit commented
Actual code looks good here.

However, we should make a note to revisit the assumption that the correct way to handle TCP disconnects is to restart the UDP server and also to enter idle mode. This may not be the right thing to do on the field (especially if we have flaky wifi that sometimes drops packets). It may be the case that on the field, we don't actually want to enter idle mode.

I'm also skeptical that UDP receiver actually needs to be restarted. It may just be sufficient to have it clear its dawn_ip such that is ready for reconnects from anywhere.

2017-03-02 04:14 UTC, nikitakit approved these changes
lgtm

2017-03-02 04:18 UTC, merged