[RUNTIME] runtime: Clean up code
pioneers/PieCentral pull request #174
Opened 2017-03-02 06:47 UTC by mc10

We don't really need those `r`, `g`, and `a` vars.

2017-03-02 17:38 UTC, yizow requested changes
I like your readibility fixes and cleanups.

Few comments re: style.

2017-03-02 17:38 UTC, yizow commented on runtime/testy/runtime.py
> +  else:
Style thing i picked up over the summer: 

With if/ else chains, you want to structure the code such that the simpler case comes first, and the more complicated case comes second. It's a readibility thing: that way, people can read the simple case and move on to the complicated case while the conditional clause is still fresh in their mind. 

tl;dr change to `if not testNames` and swap the if/else blocks

2017-03-02 17:38 UTC, yizow commented on runtime/testy/runtime.py
> +    if testSuccess(testFileName):
Oh, this is the perfect example of what i mentioned above. good fix.

2017-03-02 17:38 UTC, yizow commented on runtime/testy/studentAPI.py
> +    if name in self.buttons:
why remove the `elif`?

2017-03-02 17:38 UTC, yizow commented on runtime/testy/studentAPI.py
> +    if not inspect.iscoroutinefunction(fn):
same as above. seems like an unneccessary change

2017-03-02 17:38 UTC, yizow commented on runtime/testy/studentAPI.py
> +    return self.sensorMappings.get(name)
we want to return a studentApiError, not the normal KeyError

2017-03-02 17:38 UTC, yizow commented on runtime/testy/studentAPI.py
> +    return self.sensorMappings.get(name)
allows us to extend functionality more easily.

2017-03-02 17:38 UTC, yizow commented on runtime/testy/studentAPI.py
> +  def __init__(self, toManager, fromManager):
this seems like almost a functional change.
@brandonxxlee

2017-03-02 19:02 UTC, mc10 commented on runtime/testy/studentAPI.py
> +    return self.sensorMappings.get(name)
The code as before wouldn't throw an error in the first place, since we're using `.get` instead of a standard dictionary `[]` access.

2017-03-02 19:03 UTC, mc10 commented on runtime/testy/studentAPI.py
> +    if name in self.buttons:
I guess I personally find it simpler if we have `return` statements since there's no need for the `el` part.

2017-03-02 19:04 UTC, mc10 commented on runtime/testy/runtime.py
> +  else:
Hmm I was more following the principle of "always use positive `if` conditions with `if`-`else` statements, since they're easier to reason about".

2017-03-02 22:22 UTC, brandonxxlee commented on runtime/testy/studentAPI.py
> +  def __init__(self, toManager, fromManager):
From a quick glance it seems to still preserve functionality, but I haven't actually tested it.

2017-03-04 00:40 UTC, yizow requested changes
Still would like the `if`/`else` block swapped and the `elif` statements kept

2017-03-04 00:40 UTC, yizow commented on runtime/testy/runtime.py
> +  else:
not always. 
And in this case, its approx the same either way.

2017-03-04 00:40 UTC, yizow commented on runtime/testy/studentAPI.py
> +    if name in self.buttons:
functionally, theyre the same.

I would argue that elif is more clear. One does not need to go "oh this if has a return, so only one of these will execute" 

More conciseness is not always more readibility.

2017-03-04 00:40 UTC, yizow commented on runtime/testy/studentAPI.py
> +    return self.sensorMappings.get(name)
ah, good point.

2017-03-04 01:09 UTC, mc10 commented
@yizow Changes should be addressed with the latest commit.

2017-03-04 07:15 UTC, yizow requested changes
LGTM

2017-03-04 07:16 UTC, yizow approved these changes

2017-03-04 07:51 UTC, merged