[DAWN] Editor: Improve the unsaved changes dialog
pioneers/PieCentral pull request #184
Opened 2017-03-03 06:38 UTC by mc10

The dialog is more succinct, and the program no longer closes on reloading.
Yes, there is a bug where hitting "Save..." won't close the program afterwards, but that bug is already present in the current version on `master`; I just mentioned it in a comment for visibility purposes.

2017-03-04 02:28 UTC, kevinmasd requested changes

2017-03-04 02:28 UTC, kevinmasd commented on dawn/renderer/components/Editor.js
> +      const clickedId = dialog.showMessageBox(currentWindow, {
Hang for #162, which has some renamings regarding this component.

2017-03-04 02:28 UTC, mc10 commented on dawn/renderer/components/Editor.js
> +      const clickedId = dialog.showMessageBox(currentWindow, {
Sounds good, I'll rebase on top afterwards.

2017-03-04 23:58 UTC, mc10 commented
@kevinmasd Rebased on top of master. I've tried to avoid using `currentWindow.close()`, as that doesn't always make sense (e.g. if you just refresh the editor), and functionally this should work the same as before.

2017-03-05 08:42 UTC, kevinmasd approved these changes

2017-03-05 08:43 UTC, merged