[HIBIKE] Master-ready Potentiometer
pioneers/PieCentral pull request #202
Opened 2017-03-05 04:30 UTC by tingtingchiang

For a clean merge, copied all files relevant to Potentiometer (basically those in the folder Potentiometer) to a new branch off of master. Previous commits can be found on hibike/p2.0-refactor-pullrequest. Can be compiled with master's version of hibike.

2017-03-05 05:43 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.cpp
> +uint8_t pins[NUM_PINS] = {IN_0, IN_1, IN_2};
This implimentation of potentiometer has three devices.

The README.md specifies 4.  Please update README.md to match.

2017-03-05 05:48 UTC, dHutchings requested changes
Code in general is ok, but the things that are holdovers aren't.

Please make sure to update the README and the year in the enum.

2017-03-05 05:48 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.h
>  #define LED_PIN 13
Please remove line 11.  There is no LED Pin on the arduino micro.

2017-03-05 05:48 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.h
> +#endif /* EX_DEVICE_H */
Add newline at end of file.

2017-03-05 05:48 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.h
>  void setup();
Please update the year to 1.  The Year is the number of years since Year 8, the 2015 - 2016 season.

2017-03-05 23:29 UTC, mc10 commented
@tingtingchiang Unrelated to the PR, but you should set your email address for Git:
```
git config --global user.email EMAIL
```

Otherwise, GitHub won't link your commits to your user account.

2017-03-06 23:02 UTC, dHutchings approved these changes
Alright.  Everything's fixed.  Good job!

2017-03-06 23:02 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.cpp
> +  if (len < sizeof(float) || param > 2) {
On Linefollower, there is also a check for param < 0. Please impliment here.

2017-03-06 23:02 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.cpp
> +uint8_t pins[NUM_PINS] = {IN_0, IN_1, IN_2};
Fixed.

2017-03-06 23:02 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.cpp
> +  if (len < sizeof(float) || param > 2) {
You made a comment on another branch, reminding me that this is a uint, so it can't be negative.  I withdraw this comment.  THanks!

2017-03-06 23:02 UTC, dHutchings commented on hibike/devices/Potentiometer/potentiometer.h
>  void setup();
fixed

2017-03-06 23:03 UTC, merged