[INTEG] Dawn/Runtime proto synchronization
pioneers/PieCentral pull request #211
Opened 2017-03-07 07:08 UTC by Alramech

2017-03-07 07:13 UTC, brandonxxlee commented
I made all relevant runtime changes on #193 and integration/chris. Why did we make a new separate branch?

2017-03-07 07:14 UTC, Alramech commented
mostly because dawn got broken and I didn't want to go through the trouble of merging in a bunch of master changes

2017-03-07 18:49 UTC, brandonxxlee requested changes
Proto needs to be modified to keep up with changes on master.

2017-03-07 18:49 UTC, brandonxxlee commented on ansible-protos/runtime.proto
> -            bool bool_value = 4;
This proto field should not be deleted.

2017-03-07 18:49 UTC, brandonxxlee commented on runtime/testy/runtime.py
> -
Unnecessary whitespace diff.

2017-03-08 03:59 UTC, kevinji submitted a review, later dismissed
Mostly whitespace changes. I'm not too sure how protobuf works; is there a way to sync Dawn's enums in renderer/utils/utils.js with the protobuf enums?

2017-03-08 03:59 UTC, mc10 commented on ansible-protos/robotstate.proto
> +
Extra newline here.

2017-03-08 03:59 UTC, mc10 commented on ansible-protos/runtime.proto
> +
Extra newline here.

2017-03-08 04:24 UTC, brandonxxlee approved these changes
LGTM, just make sure the correct compiled protos are also built and merged into master.

2017-03-09 04:53 UTC, brandonxxlee commented
Master protos have been changed, need to pull master and rebuild proto

2017-03-09 04:56 UTC, kevinji submitted a review, later dismissed
Minor spacing change.

2017-03-09 04:56 UTC, mc10 commented on dawn/fake-runtime/FakeRuntime.js
> +    IDLE: 0,
Can you make this two-spaced?

2017-03-11 06:34 UTC, nikitakit commented
It looks like we missed the window for deploying these changes this year. I really wish we could get these changes in, but it doesn't look like that will be happening.

I'm closing this PR.

2017-03-11 06:34 UTC, closed without merging