[HIBIKE] heartbeat upgrade to use requests
pioneers/PieCentral pull request #230
Opened 2017-03-09 06:45 UTC by dHutchings

Smart devices now send packets asking for heartbeats, and get heartbeat responses back.

Can change the period between sending heartbeats.  Can change the time until it disables itself because no heartbeat responses.

2017-03-09 07:48 UTC, kevinji reviewed
Just some minor spacing issues.

2017-03-09 07:48 UTC, mc10 commented on hibike/lib/hibike/hibike_device.h
> +void  hibike_setup(uint32_t _disable_latency, uint32_t _heartbeatDelay);
Extra space got added here.

2017-03-09 07:48 UTC, mc10 commented on hibike/hibike_process.py
> +
Extra newlines here.

2017-03-09 11:09 UTC, dHutchings commented on hibike/lib/hibike/hibike_device.h
> +void  hibike_setup(uint32_t _disable_latency, uint32_t _heartbeatDelay);
fixed.

2017-03-09 11:10 UTC, dHutchings commented on hibike/hibike_process.py
> +
Fixed

2017-03-09 11:20 UTC, dHutchings commented
@mc10   Fixed the whitespace issues.  Thanks for reviewing!

Also fixed a merge into master that somehow got on this branch.  Just now committing actual changes for this feature.

2017-03-09 11:46 UTC, dHutchings commented
That "Merge branch 'master' " was me fixing merge conflicts.  Dunno if that's the right thing to do...?

2017-03-09 17:45 UTC, mc10 commented
That should be fine, since we're squashing and merging before any PR goes into master anyways.

2017-03-10 21:04 UTC, yizow requested changes

2017-03-10 21:04 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  hibike_setup(500, 100); //500 ms without heartbeat to disable, ask for heartbeats at 100 Hz.
I recommend we tune down to 10 hz
100 hz is an order of magintude faster than the rest of the communication stack

2017-03-10 22:30 UTC, yizow approved these changes

2017-03-10 22:41 UTC, yizow approved these changes

2017-03-10 22:42 UTC, merged