Adds basic UDP integration to the current implementation of runtime
pioneers/PieCentral pull request #25
Opened 2016-09-24 22:32 UTC by bodiddles

Creates 4 processes: packager, sender, receiver, unpackager to handle
data and send over it over UDP sockets. These currently don't use
google protos but converts "TEST" into a bytearray and sends over sockets.

To handle async messages, there is a class called two_buffer which just
stores and sends data in two separate indices of a list which are atomic
operations which should be ok for async.

It uses the process factory in runtime.py to generate said processes and
I have added them into the process names enum class. I have also added
additional SM_COMMANDS SEND and RECEIVE. SEND is sent to SM when the
packager is done with packaging one set of data and can accept another.
This should be fixed in the future to constantly send over the state,
potentially using another instance of the two_buffer.
The RECEIVE command just stores whatever we send to state manager into
the state itself which will also need to fixed to handle storing gamepad
data which we expect from Dawn over UDP.

2016-09-24 22:37 UTC, brandonxxlee commented on runtime/testy/runtimeUtil.py
> +  UDP_UNPACKAGER       = "udpUnpackager"
Get rid of extra space.

2016-09-24 22:43 UTC, nikitakit commented on runtime/testy/Ansible.py
> +data = [0] #for testing purposes
This variable is not used anywhere. (To use it inside a function, you should have a `global data` line at the top of the function)

2016-09-24 22:44 UTC, nikitakit commented on runtime/testy/Ansible.py
> +class two_buffer():
Name this `TwoBuffer` so that it follows the proper naming convention for classes. (You can consult with PEP8 for style advice)

2016-09-24 22:46 UTC, nikitakit commented on runtime/testy/Ansible.py
> +raw_fake_data = [[0]]
This variable is not used anywhere. (It does not look like an export to outside of this module, and there is no `global raw_fake_data` declaration anywhere)

2016-09-24 22:46 UTC, nikitakit commented on runtime/testy/Ansible.py
> +packed_fake_data = [[0]]
Looks unused (see also above)

2016-09-24 22:46 UTC, nikitakit commented on runtime/testy/Ansible.py
> +dawn_buffer = [0]
Looks unused (see also above)

2016-09-24 22:49 UTC, nikitakit commented on runtime/testy/Ansible.py
> +def packageData(badThingsQueue, stateQueue, pipe):
This deserves a docstring that explains that this is run in a thread (or is it a process?)

2016-09-24 22:50 UTC, nikitakit commented on runtime/testy/Ansible.py
> +def udpSender(badThingsQueue, stateQueue, pipe):
This deserves a docstring that explains that this is run in a thread

2016-09-24 22:50 UTC, nikitakit commented on runtime/testy/Ansible.py
> +def udpReceiver(badThingsQueue, stateQueue, pipe):
This deserves a docstring that explains that this is run in a thread

2016-09-24 22:50 UTC, nikitakit commented on runtime/testy/Ansible.py
> +def unpackageData(badThingsQueue, stateQueue, pipe):
This deserves a docstring that explains that this is run in a thread

2016-09-24 22:50 UTC, nikitakit commented on runtime/testy/Ansible.py
> +
So many blank lines here seems excessive

2016-09-24 22:51 UTC, nikitakit commented on runtime/testy/stateManager.py
> -
This irrelevant whitespace change pollutes the diff

2016-09-24 23:00 UTC, nikitakit requested changes
I made a few stylistic changes in the line-by-line.

But the big issue as I see it is that the send and receive buffers are each accessed from two different processes. Are you sure this works? I don't see any cross-process synchronization primitives.

I suspect that when a TwoBuffer is called from two different process, each process actually gets a clone of the instance and they don't actually share any data!

2016-09-25 00:10 UTC, yizow commented on runtime/testy/Ansible.py
> +#Handles packaging and sending state to dawn in the form of protobuf we define
newline between functions

2016-09-25 00:10 UTC, yizow commented on runtime/testy/Ansible.py
> +def packageData(badThingsQueue, stateQueue, pipe):
newline between functions

2016-09-25 00:24 UTC, yizow commented on runtime/testy/Ansible.py
> +            if (rawState == SM_COMMANDS.READY):
Im working on a commit that will hide SM_COMMANDS.READY from spawned process. Continue as is, I will deal with merge conflicts.

2016-09-25 00:33 UTC, yizow commented on runtime/testy/Ansible.py
> +def udpReceiver(badThingsQueue, stateQueue, pipe):
newline between functions

2016-09-25 00:34 UTC, yizow commented on runtime/testy/Ansible.py
> +def unpackageData(badThingsQueue, stateQueue, pipe):
newline between functions

2016-09-25 00:52 UTC, yizow requested changes
I agree with nikita's assesment: using multiple processes like this means they don't share data; i.e. sendBuffer and recvBuffer are separate for each process you spawn. 
So currently, you have 16(!) total buffers. I think this is unnecessary and can be reduced. 

You probably want to move to a model where the entire ansible is a single process. This single process may be multithreaded. 

Also, I think this is written in a functional style. The rest of the code we've written so far has been object oriented i think. 
You would make an Ansible class, and it would have a start() method that we would call as a new process. 
Do you think it's worth doing it this way, for consistency?

2016-09-25 00:52 UTC, yizow commented on runtime/testy/stateManager.py
>    def initRobotState(self):
add newline between functions

2016-09-25 00:52 UTC, yizow commented on runtime/testy/runtime.py
> +from Ansible import *
Generally I think we'd like to avoid "import *". Pollutes namespace, leading to annoying bugs.
runtimeUtil should be the only one; it should also only be importing classes.

2016-09-25 00:52 UTC, yizow commented on runtime/testy/Ansible.py
> +class two_buffer():
Namely, python classes should be CamelCase, with the first letter Capitalized.

2016-09-25 00:52 UTC, yizow commented on runtime/testy/Ansible.py
> +    def replace(self, item):
put newlines between functions.

2016-09-25 00:52 UTC, yizow commented on runtime/testy/Ansible.py
> +data = [0] #for testing purposes
If its for testing purposes, hopefully the testing has been completed before you pull requested, and this should be removed.

Re: Nikita
you want the `global data` line only if you plan on reassigning the value of data to point to, say, a different object. However, as lists are mutable objects in python, you can change the contents of data without using global.

2016-09-25 00:52 UTC, yizow commented on runtime/testy/Ansible.py
> +    def get(self):
add newline

2016-09-25 00:52 UTC, yizow commented on runtime/testy/Ansible.py
> +        self.put_index = (self.put_index + 1) % 2
another way of doing this when you only have two options, `self.put_index = 1 - self.put_index`

2016-09-25 08:44 UTC, bodiddles commented
The only issue I see with having a single Ansible Object is that sending and receiving should be separate as they are definitely independent and don't require the other. Thus, if we implement something like multi-threading, I think the issue would be that we may have to kill the entire Ansible process if one part of it needs to be restarted. I think something that may work would be making sending and packaging and receiving and unpackaging their own class and probably TCP stuff in a separate class as well.

2016-09-25 18:37 UTC, brandonxxlee commented on runtime/testy/stateManager.py
> +      elif cm_type == SM_COMMANDS.SEND:
I think the command `SEND` is too generally named since it specifically refers to sending to the UDPpackager.

2016-09-26 02:50 UTC, yizow commented
I imagine that a lot of the logic, for both sending and receiving, will overlap. You can probably make a single object, then instatiate it with arguments that tell it whether its sending or receiving. 

As for restarts, ideally Ansible should *never* need to restart, right? That ability is there only to make it harder to crash runtime, as a whole. I'm treating an Ansible process as a duplex channel. If one side (sending, or receiving) of it goes down, i think it makes sense to just pull the plug on the whole thing and setup a new process. 

Regardless, I think 4 process for the purpose of just one UDP duplex channel is definitely overkill.

2016-09-26 05:19 UTC, bodiddles commented
I don't know about the logic overlapping for sending and receiving since it is already barebones and utilizing different protos for sending and receiving means that packaging and unpackaging are intrinsically different. 
;
Obviously it shouldn't restart but if we are building for resiliency, we should have the ability to just restart one part of the channel, especially if dawn is using this as a heartbeat. I think we could have 3 different processes, one for sending, one for receiving, and one for tcp and just have packaging and upackaging as separate threads on their respective processes. I think this makes sense as it reduces the number of processes but still allows for individual restarts if something unseen does go wrong. 

In terms of classes, there aren't any issues with separate classes for each process as each one only interacts with its own set of data.

2016-10-20 04:20 UTC, closed without merging