[HIBIKE] Servo was improperly merged. Fixed and reintegrated
pioneers/PieCentral pull request #269
Opened 2017-03-16 02:58 UTC by JHGZhou

2017-03-19 04:54 UTC, yizow requested changes

2017-03-19 04:54 UTC, yizow commented on hibike/hibike_tester.py
>      h.enumerate()
Testing file changes?

2017-03-19 04:54 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> -  disableAll();
Are we removing disable all?

2017-03-23 05:01 UTC, JHGZhou commented on hibike/hibike_tester.py
>      h.enumerate()
Oops, reverted to original state

2017-03-23 05:01 UTC, JHGZhou commented on hibike/devices/ServoControl/servo_control.cpp
> -  disableAll();
Added disable all back in

2017-03-23 05:13 UTC, yizow approved these changes

2017-03-23 05:17 UTC, merged