[Dawn] Peripheral Display Filter
pioneers/PieCentral pull request #309
Opened 2017-04-08 22:28 UTC by kevinmasd

TeamFlag has been edited out of peripheral display. It had been conflicting with any other sensor in the default case (i.e. not in `cleanerNames`).

Additionally, can somebody check if all the displayable peripherals are enumerated in `cleanerNames`?

2017-04-09 12:09 UTC, yizow commented
I'm not quite sure what this is supposed to do.
Currently, team flag does not show up as a sensor.

This pull request... also makes it not show up?

2017-04-09 16:51 UTC, kevinmasd commented
What's happening currently is that the accordion/panel for ExampleSensor and TeamFlag are conflicting one another, since Dawn doesn't recognize either. As a result, TeamFlag would never be seen because Electron only displays the panel that came earliest (alphabetically being ExampleSensor).

2017-04-09 19:15 UTC, kevinji requested changes
Really minor stylistic differences.

2017-04-09 19:15 UTC, mc10 commented on dawn/renderer/components/PeripheralList.js
> +const filter = [PeripheralTypes.TeamFlag];
Can you make this a set (`new Set([PeripheralTypes.TeamFlag])`)?

2017-04-09 19:15 UTC, mc10 commented on dawn/renderer/components/PeripheralList.js
>    array.forEach((p) => {
You can extract the filter includes check with
`array.filter(p => !filter.has(p.device_type)).forEach(p => /* ... */)`
assuming you converted the filter to a Set.

2017-04-09 22:02 UTC, kevinmasd commented
Changes done.

2017-04-10 22:12 UTC, kevinji approved these changes

2017-04-10 23:06 UTC, merged