[Dawn] Logging to File
pioneers/PieCentral pull request #311
Opened 2017-04-09 00:36 UTC by kevinmasd

Addresses #300 

Edits to `Ansible.js`:
* Logger class and instance created for Ansible related output.
  * Initiated during Ansible setup

Edits to `utils.js`:
* Logger class and instance created for renderer-related output.
  * Initiated in App.js, which is guaranteed to be the earliest file loaded.

2017-04-09 01:41 UTC, mc10 commented
Does the last commit work? I feel like you'd need to call `logging().log(str)` with your current implementation.

2017-04-09 12:19 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +    this.logger = logger;
not exactly sure what binding does; does it mean the bound function can start being scheduled? if so, we may want `this.logger` to be set before bidning.

2017-04-09 17:02 UTC, kevinmasd commented on dawn/main/ansible/Ansible.js
> +    this.logger = logger;
Logger is always set before this part. It is initialized at the very bottom, right before any of the other classes are running.

2017-04-09 18:49 UTC, kevinji requested changes
Left a few comments. Also, this is probably more of a long-term thing, but it might make sense to better differentiate log messages between `info`, `warning`, and `error` to make it easier to distinguish what is and isn't important.

2017-04-09 18:49 UTC, mc10 commented on dawn/renderer/utils/utils.js
> +export const logging = () => {
Per my comment from earlier: This is a function, so if you wanted to access the logger you'd probably need `logging().log` with your current implementation; it'd probably make more sense to just set `logging = new Logger();` and remove `_log`.

Also, could you possibly remove the duplicate version of `Logger` from `Ansible`, export this version, and give this one a constructor argument for file name?

2017-04-09 18:49 UTC, mc10 commented on dawn/renderer/utils/utils.js
> +    this.log_file.write(d.toString());
Is this really necessary, considering it's part of the file name already?

2017-04-09 18:49 UTC, mc10 commented on dawn/renderer/utils/utils.js
> +    this.log_file = fs.createWriteStream(`./${d.valueOf()}-dawn.log`, { flags: 'w' });
I think `d.getTime()` (or even `Date.now()` if the below line isn't needed) is more commonly used.

2017-04-09 18:49 UTC, mc10 commented on dawn/main/ansible/Ansible.js
> +      this.logger.error('Runtime failed to confirm');
This doesn't appear like it'll work, as the `logger` class has no `error` method.

2017-04-09 22:28 UTC, kevinmasd commented
For some reason thought the logging function would replace itself with the interior. Creating the export must be separate from variable initialization (`export const logger = new Logger()` causes a new Logger to be created on every message).

2017-04-09 22:49 UTC, mc10 commented
Could you do this instead:
```
const logger = new Logger();
export logger;
```
I forget exactly how export rules work.

2017-04-09 22:54 UTC, kevinmasd commented
Throws parsing errors, so probably doesn't work.

2017-04-10 22:13 UTC, kevinji approved these changes

2017-04-10 23:06 UTC, merged