[HIBIKE] Delete old sensors
pioneers/PieCentral pull request #432
Opened 2017-10-14 21:29 UTC by youqichen

This PR removes obsolete devices, specifically teamflag and encoders.

2017-10-14 21:34 UTC, baby-bell requested changes
You need to remove `TeamFlag` from the README as well, it's still there. Otherwise lgtm

2017-10-14 21:43 UTC, baby-bell requested changes
You are almost there, just need to remove the `TeamFlag` fields that are left over

2017-10-14 21:43 UTC, baby-bell commented on hibike/README.md
>  |         |                | 1            | blue       | bool       | yes   | yes    |
Remove the `TeamFlag` fields as well, please

2017-10-14 22:11 UTC, tingtingchiang approved these changes
LGTM

2017-10-19 02:19 UTC, tingtingchiang commented
Issue #432

2017-10-19 02:55 UTC, baby-bell approved these changes

2017-10-19 03:24 UTC, merged