shepherd/lcm
pioneers/PieCentral pull request #465
Opened 2017-11-18 22:55 UTC by charleshong3

Implemented LCM API for Shepherd

2017-11-29 22:55 UTC, JHGZhou requested changes

2017-11-29 22:55 UTC, JHGZhou commented on shepherd/LCM.py
> +class LCMClass:
Add a comment here describing how this class works very generally. Also describe how to make use of the LCM object.

2017-11-29 22:55 UTC, JHGZhou commented on shepherd/LCM.py
> +        # def start_thread(self):
remove unneeded code

2017-11-29 22:55 UTC, JHGZhou commented on shepherd/LCM.py
> +        """
remove uneeded code

2017-11-29 22:55 UTC, JHGZhou commented on shepherd/LCM.py
> +        # Send a list into a target
comment style should be three single quotes above and below the docstring and the docstring should be under the def statement and above the rest of the method

2017-12-02 21:59 UTC, brandonxxlee submitted a review, later dismissed
lgtm, Just make sure you test thoroughly.

2018-01-24 06:28 UTC, kevinmasd commented
Handled in #473

2018-01-24 06:28 UTC, closed without merging