[SHEPHERD] (Codegen) update the embedded decode_message
pioneers/PieCentral pull request #522
Opened 2018-02-22 05:04 UTC by Naftoreiclag

[SHEPHERD] (Codegen) update the embedded decode_message method to use the latest staff_decode from shepherd/Codegen.py

2018-02-22 06:45 UTC, brandonxxlee requested changes

2018-02-22 06:45 UTC, brandonxxlee commented on runtime/studentAPI.py
> +        output = int(output) % 10000
See comment in #492 , this should reflect change in other PR if it is changed.l

2018-02-23 00:49 UTC, brandonxxlee approved these changes

2018-02-24 19:58 UTC, JHGZhou approved these changes
Looks good

2018-02-24 19:58 UTC, merged