Shepherd/launchbuttons
pioneers/PieCentral pull request #658
Opened 2018-11-29 04:44 UTC by FIREdog5

2018-11-29 04:51 UTC, jonathan-j-lee commented
Pull from `master` to get the Dawn version fix. Note that you have a bunch of conflicting files you'll need to fix. @FIREdog5

2018-11-30 10:28 UTC, jonathan-j-lee requested changes
Comments so far.

2018-11-30 10:28 UTC, jonathan-j-lee commented on shepherd/Code.py
> +    global effect_list
Most of these variables don't need `global`. `global` is needed for changing what these variables point to (e.g. if you wanted `codes = 1`), but is not needed for internal mutations (e.g. appending elements to lists or setting key-value pairs).

2018-11-30 10:28 UTC, jonathan-j-lee commented on shepherd/Code.py
> +        code_effect[codes[i]] = effect_list[random.randint(0, len(effect_list))]
Use `random.choice(effect_list)`.

2018-11-30 10:28 UTC, jonathan-j-lee commented on shepherd/Code.py
> +effect_list = list(EFFECTS.ALL_EFFECTS)
Is there a reason this state and code isn't wrapped in a class?

2018-11-30 10:28 UTC, jonathan-j-lee commented on shepherd/Code.py
> +effect_list = []
Doesn't seem to be used.

2019-01-24 03:52 UTC, FIREdog5 commented on shepherd/Code.py
> +        code_effect[codes[i]] = effect_list[random.randint(0, len(effect_list))]
Done.

2019-01-24 04:09 UTC, jonathan-j-lee approved these changes

2019-02-02 22:54 UTC, merged