Runtime/yizhe/beagle compatibility
pioneers/PieCentral pull request #67
Opened 2016-11-04 09:34 UTC by yizow

2016-11-05 03:58 UTC, nikitakit requested changes

2016-11-05 03:58 UTC, nikitakit commented on runtime/testy/runtime.py
> -        newBadThing = badThingsQueue.get(block=True)
This code is duplicated with `runtimeTest`... and this PR only fixes the bugs in the `runtimeTest` version. You should at least keep the two in sync, and preferably de-duplicate the code asap.

2016-11-05 03:58 UTC, nikitakit commented on runtime/testy/runtimeUtil.py
> +  STUDENT_CODE_TIMEOUT        = 1
BTW the name `STUDENT_CODE_TIMEOUT` is too similar to `BAD_EVENTS.STUDENT_CODE_TIMEOUT`. Also, why is `RUNTIME_CONFIG` an Enum? That makes no sense. I strongly recommend cleaning this up in a future PR.

2016-11-05 21:36 UTC, cjsanchez commented
I just added the changes made to runtimeTest() to runtime() and tested that everything ran correctly on the beaglebone. Everything looks good.

2016-11-05 22:29 UTC, bodiddles requested changes

2016-11-05 22:29 UTC, bodiddles commented on runtime/testy/runtime.py
> +      global terminated
Shouldn't this be nonlocal as we only want to change it in the parent frame and not global

2016-11-05 22:29 UTC, bodiddles commented on runtime/testy/runtime.py
> +          if student_process.is_alive():
This code is a repeat of above, we should just have a function that handles this, even if it is not ideal.

2016-11-06 00:16 UTC, cjsanchez commented on runtime/testy/runtime.py
> +          if student_process.is_alive():
fixed

2016-11-06 03:09 UTC, nikitakit approved these changes
LGTM

2016-11-07 02:48 UTC, yizow commented
Force pushed after rebasing. Nothing was changed; all tests still pass.

2016-11-07 02:57 UTC, bodiddles approved these changes

2016-11-07 04:26 UTC, merged