[Networking] Basic message server and driver install script
pioneers/PieCentral pull request #69
Opened 2016-11-06 03:19 UTC by Alramech

- currently requires manual ip input, defualt localhost

- client closes after sending message, to be changed to persistent

2016-11-07 02:35 UTC, yizow requested changes
Main issue: Update to python 3.4

This is a lot more barebones that I was hoping for :-/

Have you tested this running on different machines? 
Or can you spin up more than just two processes: Simulate a (Driver station, field control, robot) network?
After making such a simulation, how would you verify it works? Then, write a test script that does that verfication.

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +s = socket.socket(
why split this into multiple lines?

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +s.connect(('localhost', 3141))
if 3141 is going to be a constant, bind it to a global variable after your import statements.

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +s.close()
add newline at end of file

2016-11-07 02:35 UTC, yizow commented on networking/server.py
> +s = socket.socket(
Same comment as above

2016-11-07 02:35 UTC, yizow commented on networking/server.py
> +s.bind(('localhost', 3141))
Same comment as above
Use global costants.

2016-11-07 02:35 UTC, yizow commented on networking/server.py
> +s.listen(5)
Why choose 5? Leaving it blank lets the system choose a "reasonable value"

2016-11-07 02:35 UTC, yizow commented on networking/server.py
> +    print(msg)
New line at end of file

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +s.close()
Using `with s as socket.socket(...):` autoamtically calls close at end of block

2016-11-07 02:35 UTC, yizow commented on networking/server.py
> +    (cs, addr) = s.accept()
I recommend renaming `cs` to `conn`. More readable.

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +msg = raw_input('message: ')
we're using python3.4 currently. `raw_input` is deprecated and has been renamed to `input`

2016-11-07 02:35 UTC, yizow commented on networking/client.py
> +    sent = s.send(msg)
This will no longer work in python3. msg must support buffer interface, so use `bytes(msg)`

2016-11-10 04:02 UTC, Alramech commented on networking/server.py
> +s.listen(5)
That's a 3.5 thing, not a 3.4. 5 is usually the system maximum value.

2016-11-10 05:13 UTC, yizow requested changes

2016-11-10 05:13 UTC, yizow commented on networking/server.py
> +HOST = 'localhost'
why are port and host in the opposite ordering here ._.

2016-11-10 05:13 UTC, yizow commented on networking/server.py
> +        while rec != bytes():
i think `while rec` works, and is cleaner. You should check. I'm going off the python doc example which is `    if not data: break`

2016-11-10 05:13 UTC, yizow requested changes

2016-11-10 05:13 UTC, yizow commented on networking/server.py
> +        print(msg.decode('UTF8'))
Do we have a newline at end of file?

2016-11-11 18:25 UTC, yizow approved these changes
Good work. In future patches, i'd like to see: 
1. Some sort of test. Send things, print things to a file, examine file. AUTOMATED.
2. More than 2 clients.
3. An interactive mode where we can send user-input messages. This will make debugging and testing the performance of runtime/ dawn super super useful. 

Merge when you're ready.

2016-11-12 22:02 UTC, merged