Fake Runtime on Dawn Side
pioneers/PieCentral pull request #70
Opened 2016-11-09 23:25 UTC by kevinmasd

Testing currently consists of toggling a variable on every Runtime update, sending the toggle to Runtime back.

2016-11-11 20:42 UTC, yizow requested changes
Full disclosure: I'm not entirely sure what i'm looking at :-/

My comments were focuses on cleaning up the code.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +// const net = require('net');
Remove unnecessary commented out lines.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +// const TCPData = runtimeBuilder.build('TCPData');
Remove.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +// const tcpPort = 12347;
Remove.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +// const tcp = net.connect({port: tcpPort}, () => {
Remove.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +    // type: 'UPDATE_STATUS',
Remove.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +        value: Math.round(randomFloat(0, 1)),
Sending random floats makes testing really annoying.

2016-11-11 20:42 UTC, yizow commented on dawn/fake-runtime/FakeRuntime.js
> +}, 1000);
Make the interval a constant somewhere.

2016-11-11 20:42 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +let test = 0;
let declares test to be block scope, and automatically unbinds it when you leave the block.

1. This is global, not a block, so there's not much point of using let.
2. Is unbinding behaviour what you want?

2016-11-11 20:42 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +let test = 0;
Actually, more reading shows this wont work: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
`At the top level of programs and functions, let, unlike var, does not create a property on the global object.`

2016-11-11 20:42 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +let test = 0;
And if youre not using test, this line should be removed.

2016-11-11 20:42 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +}, 1000);
use a constant

2016-11-11 20:42 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +    test = 1 - test;
i think test is unbound here

2016-11-11 20:42 UTC, yizow commented on dawn/renderer/utils/sagas.js
> +    console.log('Hello');
How often is this going to be printed? Do you want to rate limit this?

2016-11-11 22:07 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +let test = 0;
Our current linting rules prefer `let` over `var`, as its behavior is generally considered more predictable (that's subjective though).

2016-11-11 22:12 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +    test = 1 - test;
The scope of `test` here is global (test was defined on global scope), so I think it should be fine.

2016-11-11 22:13 UTC, AllanYangZhou commented on dawn/renderer/utils/sagas.js
> +    console.log('Hello');
This is already limited to 20 times/second due to delay on line 211/212.

2016-11-11 22:19 UTC, AllanYangZhou reviewed
I see in Ansible.js there is code to dispatch received sensor data to the frontend. Is that whole flow (from FakeRuntime all the way to the frontend) work? Does that mean that toggling the test variable is no longer necessary?

2016-11-11 22:19 UTC, AllanYangZhou commented on dawn/renderer/utils/sagas.js
> +    console.log('Hello');
@kevinmasd Though you should remove this before merging.

2016-11-11 22:19 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +let test = 0;
I agree that the use of the `test` variable here is largely unnecessary, why not just print what you receive for this test?

2016-11-11 22:36 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +let test = 0;
Isn't this top level though? According to that doc i linked, let literally will not bind `test` to anything.

2016-11-11 22:36 UTC, yizow commented on dawn/main/ansible/Ansible.js
> +    test = 1 - test;
See above regarding let not binding things in the global scope

2016-11-11 22:54 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +let test = 0;
My understanding of the doc you linked is that `let` in global scope does not bind the variable to the *global object*. Note that all properties of the global object are also global variables, but not all global variables are necessarily properties of the global object.

This distinction is minor, the only issue is if you try to do `global.test` (or `this.test` when this refers to `global`), but nobody ever does this.

2016-11-11 23:00 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +let test = 0;
But yeah the difference is super-confusing, I thought the same thing when I read your doc but I think there's a nice-ish explanation in section 9.7 of http://exploringjs.com/es6/ch_variables.html

2016-11-12 03:15 UTC, kevinmasd commented on dawn/main/ansible/Ansible.js
> +let test = 0;
The point of test was a proof of concept that Dawn can react to proto messages without going fully fledged into a fake controller. It'll be removed after more testing verifies that what Dawn does for communication is correct.

2016-11-12 03:23 UTC, kevinmasd commented
Haven't had time to check how Dawn actually deals with dispatch data. Currently waiting on UIDs to be re-added to the proto so I can actually map peripheral data to peripheral and checking to see whether the Sagas are actually running.

2016-11-12 06:31 UTC, AllanYangZhou commented on dawn/main/ansible/Ansible.js
> +let test = 0;
So will that (the removing part) be before this is merged in or will it be in a later PR?

2016-11-12 21:30 UTC, yizow approved these changes

2016-11-12 21:32 UTC, merged