[HIBIKE] protocol changes and runtime integration
pioneers/PieCentral pull request #81
Opened 2016-11-19 04:12 UTC by karthik-shanmugam

- change protocol to generalize all devices as param value mappings
    - implement protocol changes in firmware and python
- implement virtual devices for testing
- implement hibike_process.py and hibike_simulator.py for concurrency and runtime integration

2016-11-19 04:53 UTC, nikitakit requested changes
Here's a first-pass review of what I see as the core python code. I'll read through the virtual devices and the C++ code a little later.

2016-11-19 04:53 UTC, nikitakit commented on hibike/ATALANTA_INTEGRATION.md
> +- callibrate: bool write only
s/callibrate/calibrate

2016-11-19 04:53 UTC, nikitakit commented on hibike/README.md
> +|         |                | 6            | callibrate | bool       | no    | yes    |
s/callibrate/calibrate

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibikeDevices.json
> +                                                          {"number": 6  , "name": "callibrate" , "type": "bool"    , "read": false, "write": true  }
s/callibrate/calibrate

2016-11-19 04:53 UTC, nikitakit commented on hibike/display.py
> +h.addVirtualPort('/dev/pts/26')
Is there any way to avoid hardcoding a port here? (Maybe accept the port via a command line arg?)

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  "LimitSwitch"   :       0x00,
This seems to be a redundant copy of data already in the json file

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
refactor out repeated code?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
refactor out repeated code?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +     if (1 & (params >> param_count) == 1):
This is a nitpick, but I think `if params & (1 << param_count)` is cleaner

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +#     Decodes an inputted set of parameters that is in binary form
docstring not comment

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
refactor out repeated code?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +def old_decode_device_write(device_id, message):
Why is this function here? Is it even needed?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +
Why so many blank lines?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
refactor out repeated code?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  paramNums = [paramMap[device_id][name][0] for name in params]
So these next few lines, which assign to `paramNums`, `entries`, and `tot`, occur in a multitude of functions here. This code for constructing a bitmask from param names should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
`for entry in entries`

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +    tot = tot ^ entries[i]
You should use `|` (or), not `^` (xor), for constructing bitmasks. XOR can be used for both clearing and setting bits, while OR only sets them. When I saw xor I had to pause for a moment and think about toggling bits that were already enabled.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +  for t in paramT:
Construction of a type string from param types should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +    typeString += paramTypes[t]
Construction of a type string from param types should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +    struct_format += paramTypes[paramMap[device_id][param][1]]
Construction of a type string from param types should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +    typeString += paramTypes[type]
Construction of a type string from param types should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message.py
> +    struct_format += paramTypes[paramMap[device_id][param][1]]
Construction of a type string from param types should be abstracted into a function.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_message_old.py
> +from __future__ import print_function
Why is this file part of this pull request? The name suggests that it is obsolete and can be removed.

(I'm not further code reviewing the contents of this file)

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_process.py
> +                uid = args[0]
Maybe do `uid, delay, params = args`?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_process.py
> +                uid = args[0]
Maybe do `uid, params = args`?

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_simulator.py
>  import time, random
I'm assuming Yizhe's version of this file is authoritative, so not reviewing anything here.

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_tester.py
> +
Blanks lines here really isn't good style. (I noticed in previous files too)

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_tester.py
> +
Same thing here: no point for blank line (unless it's to remind yourself that you need a docstring... in which case you should write a docstring)

2016-11-19 04:53 UTC, nikitakit commented on hibike/hibike_tester.py
> +        self.pipeTochild.send(["ready"])
I thought the ready command was deprecated?

2016-11-19 04:53 UTC, nikitakit commented on hibike/list_devices.py
> +                print(reading.getPayload())
no newline at eof

2016-11-19 04:53 UTC, nikitakit commented on hibike/virtual_devices.txt
> +/dev/pts/16 /dev/pts/29
I don't think this file should be part of the commit. In fact, I think it should be part of `.gitignore` instead.

2016-11-19 04:54 UTC, nikitakit commented on hibike/ATALANTA_INTEGRATION.md
> +- callibrate: bool write only
Oh by the way @karthik-shanmugam, you and @yizow should figure out how to resolve the conflicts in this file and the json (his PR changed the formatting, fixed spelling of calibrate, etc.)

2016-11-19 04:57 UTC, nikitakit requested changes

2016-11-19 04:57 UTC, nikitakit commented on hibike/hibike_process.py
> +    ports = glob.glob("/dev/ttyACM*") + glob.glob("/dev/ttyUSB*") + open("virtual_devices.txt", "r").read().split()
You should only use `virtual_devices.txt` if it is present. (Since that file should be gitignored, it may not be present all the time.)

2016-11-19 04:57 UTC, nikitakit commented on hibike/display.py
> +h.addVirtualPort('/dev/pts/26')
Also, why are you not using `virtual_devices.txt` here?

2016-11-19 04:59 UTC, karthik-shanmugam commented on hibike/display.py
> +h.addVirtualPort('/dev/pts/26')
this file is deprecated and should be removed

2016-11-19 05:08 UTC, nikitakit commented on hibike/hibike_message.py
> +    tot = tot ^ entries[i]
this is repeated code

2016-11-19 10:57 UTC, karthik-shanmugam commented on hibike/ATALANTA_INTEGRATION.md
> +- callibrate: bool write only
if committing it broken now and letting his future changes fix it acceptable

2016-11-19 19:14 UTC, karthik-shanmugam commented on hibike/list_devices.py
> +                print(reading.getPayload())
resolved

2016-11-19 19:16 UTC, karthik-shanmugam commented on hibike/hibike_tester.py
> +        self.pipeTochild.send(["ready"])
resolved

2016-11-19 19:18 UTC, karthik-shanmugam commented on hibike/hibike_tester.py
> +
Which blank lines were you referring to? 3, 5, or 7? I've deleted 7 but kept 3 and 5 for now

2016-11-19 19:18 UTC, karthik-shanmugam commented on hibike/hibike_process.py
> +                uid = args[0]
resolved

2016-11-19 19:18 UTC, karthik-shanmugam commented on hibike/hibike_process.py
> +                uid = args[0]
resolved

2016-11-19 19:18 UTC, karthik-shanmugam commented on hibike/hibike_message_old.py
> +from __future__ import print_function
resolved, the file has been removed

2016-11-19 19:19 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    struct_format += paramTypes[paramMap[device_id][param][1]]
resolved

2016-11-19 19:19 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    typeString += paramTypes[type]
resolved

2016-11-19 19:19 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
resolved

2016-11-19 19:20 UTC, nikitakit commented on hibike/hibike_tester.py
> +
Blank line after class def looks odd to me at least

2016-11-19 19:21 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +
resolved

2016-11-19 19:22 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    struct_format += paramTypes[paramMap[device_id][param][1]]
resolved

2016-11-19 19:22 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    typeString += paramTypes[t]
resolved

2016-11-19 19:22 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +def old_decode_device_write(device_id, message):
resolved, redundant function was deleted

2016-11-19 19:22 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for t in paramT:
resolved

2016-11-19 19:22 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +#     Decodes an inputted set of parameters that is in binary form
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    tot = tot ^ entries[i]
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  for i in range(len(entries)):
resolved

2016-11-19 19:23 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  paramNums = [paramMap[device_id][name][0] for name in params]
resolved, all bitmask operations have been abstracted into encode_params and decode_params

2016-11-19 19:24 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +  "LimitSwitch"   :       0x00,
resolved, deleted the redundant dictionary which was not being used anywhere

2016-11-19 19:24 UTC, karthik-shanmugam commented on hibike/display.py
> +h.addVirtualPort('/dev/pts/26')
resolved, the file has been removed

2016-11-19 19:38 UTC, karthik-shanmugam commented on hibike/hibike_simulator.py
>  import time, random
The goal is for virtual devices to make a hibike simulator obsolete

2016-11-19 19:44 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +     if (1 & (params >> param_count) == 1):
resolved

2016-11-19 19:46 UTC, karthik-shanmugam commented on hibike/hibikeDevices.json
> +                                                          {"number": 6  , "name": "callibrate" , "type": "bool"    , "read": false, "write": true  }
not sure how to resolve conflicts between this and runtime's future PR

2016-11-19 19:58 UTC, karthik-shanmugam commented on hibike/hibike_process.py
> +    ports = glob.glob("/dev/ttyACM*") + glob.glob("/dev/ttyUSB*") + open("virtual_devices.txt", "r").read().split()
added a try catch around opening the file

2016-11-19 20:06 UTC, karthik-shanmugam commented on hibike/hibike_message.py
> +    tot = tot ^ entries[i]
resolved

2016-11-19 20:16 UTC, nikitakit requested changes
Second-pass review of core python code, and first-pass review of the virtual devices python code.

2016-11-19 20:16 UTC, nikitakit commented on hibike/hibike_message.py
> +     named_params.append(devices[device_id]["params"][param]["name"])
BTW, you can combine these two loops

``` python
res = []
for param_count, param_info in enumerate(devices[device_id]["params"]):
    if params_bitmask & (1 << param_count):
        res.append(param_info["name"])
return res
```

2016-11-19 20:16 UTC, nikitakit commented on hibike/TODO.md
> +# Thing to do for Hibike
Are the TODOs in this file still accurate?

2016-11-19 20:16 UTC, nikitakit commented on hibike/__init__.py
> +from . import hibike_message
no newline at eof

2016-11-19 20:16 UTC, nikitakit commented on hibike/spawn_virtual_devices.py
> +        time.sleep(1000)
There should be a newline at eof

2016-11-19 20:16 UTC, nikitakit commented on hibike/spawn_virtual_devices.py
> +    lines = [str(socat.stderr.readline()), str(socat.stderr.readline())]
Why do you need a cast to `str` here? I suspect that it's redundant.

2016-11-19 20:16 UTC, nikitakit commented on hibike/spawn_virtual_devices.py
> +    device = subprocess.Popen(shlex.split("python3.5 %s -d %s -p %s" % (os.path.join(os.path.dirname(__file__), "virtual_device.py"), device_type, p1)), stdout=subprocess.PIPE)
I think you should inserts some line breaks in here (maybe after some commas or parens). No need to use `\` or change the syntax, you can just use the already existing delimiters.

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +"""
Convention is to put a docstring like this at the start of the file.

2016-11-19 20:16 UTC, nikitakit commented on hibike/list_devices.py
> +            params, delay, device_type, year, id = struct.unpack("<HHHBQ", reading.getPayload())
This code looks like a duplicate of `parse_subscription_response`

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +        subscribed_params = []
What indentation is being used in this file? The standard for python is 4 spaces (not tabs), but this looks different.

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +                        data = []
This could be `data = [x for x in params_and_values if x[0] in subscribed_params]`

2016-11-19 20:16 UTC, nikitakit commented on hibike/hibike_message.py
> +messageTypes = {
You should consider using a python enum (new in python 3.4)

https://docs.python.org/3.4/library/enum.html

2016-11-19 20:16 UTC, nikitakit commented on hibike/hibike_message.py
> +  "UnexpectedDelimiter" : 0xFD,
You should consider using a python enum (new in python 3.4)

https://docs.python.org/3.4/library/enum.html

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +                     if hm.paramMap[device_id][data_tuple[0]][2] != True:# Raise a syntax error if one of the values to be read is not readable
use `not` instead of `!= True` (unless your data could possibly be a non-bool)

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +                     if hm.paramMap[device_id][new_tuple[0]][3] != True: # Raise a syntax error if the value that the message attempted to write to is not writable
Use `not` instead of `!= True`

2016-11-19 20:16 UTC, nikitakit commented on hibike/virtual_device.py
> +                        while (hm.paramMap[device_id][write_tuples[index][0]][2] != True):
Use `not` instead of `!= True`

2016-11-19 20:23 UTC, nikitakit commented on hibike/hibike_message.py
> +messageTypes = {
I suppose that this is the kind of change that it makes sense to open a github issue about, rather than trying to fold into this PR.

2016-11-19 20:54 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +"""
@ivanache

2016-11-19 20:54 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +        subscribed_params = []
@ivanache

2016-11-19 20:54 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +                        data = []
@ivanache

2016-11-19 20:54 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +                     if hm.paramMap[device_id][data_tuple[0]][2] != True:# Raise a syntax error if one of the values to be read is not readable
@ivanache

2016-11-19 20:55 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +                     if hm.paramMap[device_id][new_tuple[0]][3] != True: # Raise a syntax error if the value that the message attempted to write to is not writable
@ivanache

2016-11-19 20:55 UTC, karthik-shanmugam commented on hibike/virtual_device.py
> +                        while (hm.paramMap[device_id][write_tuples[index][0]][2] != True):
@ivanache

2016-11-19 22:20 UTC, Alramech requested changes
First pass, mostly style

2016-11-19 22:20 UTC, Alramech commented on hibike/__init__.py
> +from . import hibike_message
Add newline

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments with new parameters

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >=2 && param<){
Remove this code if it isn't doing anything yet.

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  }
What does this bracket close? If it should be here, indent previous lines properly

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ColorSensor/color_sensor.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments here as well

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ColorSensor/color_sensor.cpp
>    uint16_t *rgbc = (uint16_t *) data_update_buf;
give rgbc a less ambiguous name

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/DigitalDistance10cm/digital_distance_10cm.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/LimitSwitch/limit_switch.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/LimitSwitch/limit_switch.cpp
> +//   if (buf_len < sizeof(uint8_t) * NUM_SWITCHES) {
Remove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/LineFollower/line_follower.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/LimitSwitch/limit_switch.cpp
> +  if (MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t) || param >= NUM_SWITCHES) {
check for param < 0

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/LineFollower/line_follower.cpp
> +
Remove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/MetalDetector/metal_detector.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/MetalDetector/metal_detector.cpp
> +
either function should do nothing and then you remove return 0, or you are making this function do nothing and you should remove the rest.

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/Potentiometer/potentiometer.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/Potentiometer/potentiometer.cpp
> +  if (MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t) || param>2 || param<0) {
fix spacing for < > signs

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define IN_3 A3
REmove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/RFID/rfid.cpp
> +
Update comments for new param

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/RFID/rfid.cpp
> +  if( ! mfrc522.PICC_IsNewCardPresent()){
spacing

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/RFID/rfid.cpp
> +  if(MAX_PAYLOAD_SIZE - buf_len < sizeof(uint32_t)|| param!=0){
spacing

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(param< NUM_PINS && len< sizeof(servos[param]) || len< sizeof(toggle0)){
spacing

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
>      case TOGGLE0:
Are you sure toggle0 is always > NUM_PINS?

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
> +    //   toggle2 = value[0];
remove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
> +    //   return sizeof(toggle_servo(3, toggle3));
remove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)|| param>NUM_PINS*2 || param < 0){
Spacing

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(param<2){
magic number, replace with appropriately name constant

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/ServoControl/servo_control.cpp
>  }
newline

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/TeamFlag/team_flag.cpp
> +      return sizeof(uint8_t);
Set enum defaults to 0,1, etc, and you can remove switch with just setLED(param)
also comment to explain why

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/TeamFlag/team_flag.cpp
> +      return sizeof(uint8_t);
same as previous comment

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/TeamFlag/team_flag.h
> +#define PARAM_LED1 3
replace with enum

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.cpp
> +int EN = IO4;
If these values are not supposed to be changed, they should be const or #define

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.cpp
> +// int IN_ENB = IO9;
remove commentes

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.cpp
> +  // digitalWrite(IN_ENB, HIGH);
remove comments

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.cpp
> +      }
remove comment and just return fault instead of if, or fix clearfault

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.cpp
> +}
newline

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/YogiBear/YogiBear.h
> +  FAULT = 1,
enums give values starting from 0 as default

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_device.cpp
> +          // value = *((uint32_t*) &hibikeBuff.payload[DEVICE_PARAM_BYTES]);
remove commented code

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_device.cpp
> +          // send_device_response(param + 1, device_status(param));
remove comment

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_device.cpp
> +        //   break;
remove comment

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_device.cpp
> +  // }
remove comments

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_device.h
> +//extern uint8_t device_data_update(int param, uint8_t* data_update_buf, size_t buf_len);
remove comment

2016-11-19 22:20 UTC, Alramech commented on hibike/lib/hibike/hibike_message.h
>  #endif /* HIBIKE_H */
newline

2016-11-19 22:20 UTC, Alramech commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define IN_3 A3
remove comments

2016-11-19 22:24 UTC, karthik-shanmugam commented on hibike/spawn_virtual_devices.py
> +    lines = [str(socat.stderr.readline()), str(socat.stderr.readline())]
I think readline() was returning bytestrings but I wanted unicode for some reason

2016-11-19 23:10 UTC, nikitakit requested changes
This is my first-pass review of the C++ code.

I am very disappointed that in addition to style problems, the code contains snippets that I suspect do not function correctly. (In fact, at least one file probably won't even compile).

I would like to remind everyone that only working code should be pull requested - this is one of the main principles of how code review works. When I read a PR I expect that you have already tested the code in question and confirmed that it works on actual hardware. The presence of such red flags violates this trust, and casts doubt on the functionality of the entire set of C++ code in this PR.

I will now have to spend an extended amount of time reviewing the code in much greater detail, because I can no longer trust that even the trivial changes work correctly. In fact, you should seriously consider moving the C++ code to a different PR, because the increased scrutiny of such a review will lengthen the time it takes for the python changes to be merged.

(Thankfully, on the python side of things I've only observed style issues and not functionality problems.)

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  if (param == 0 && MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)){
What does the `MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)` condition do? And are you sure you want to test for being greater than the max payload size, rather than less? If so, I think a rewording of this condition would make sense.

(same for next several if statements)

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +    append_buf(data_update_buf, &offset, (uint8_t *)&connected, sizeof(uint8_t));
Using offset before declaration

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
>    uint8_t offset = 0;
Here you're declaring/setting offset, but there is a use of it above in the same function!

This is super confusing, and each time you do this you run the risk of getting incorrect behavior.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/ColorSensor/color_sensor.cpp
> +  if (buf_len < sizeof(uint16_t)|| param >3|| param<0) {
whitespace around comparisons is off. Normalize it to `param > 3 || param < 0` or similar

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/DigitalDistance10cm/digital_distance_10cm.cpp
> +	return 0;
What is going on here???

You're returning zero right away... but then there's more code in the function! And the indentation of the return statement is wrong, too.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/LimitSwitch/limit_switch.cpp
> +// uint8_t data_update(uint8_t* data_update_buf, size_t buf_len) {
Why is this commented out code here?

Git history is sufficient for remembering what old code used to be here.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/LineFollower/line_follower.cpp
> +    pinMode(pins[i], INPUT);
Just saw this in the diff. I trust that this change actually has some logic behind it, and is not just for debugging.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >=2 && param<){
The syntax error here suggests that this file doesn't even compile.

You shouldn't pull request code that is not in a working state.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define NUM_PARAMS 5
You should delete the commented-out definitions.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define NUM_PINS 4
Again, delete commented out code.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/RFID/rfid.cpp
> +  params[0] = &((uint32_t*)mfrc522.uid.uidByte);
`&` is the address-of operator. So you appear to be taking a pointer, and storing it into the param array. Could you double-check this code?

(`*` is the dereference operator, which is more likely to be what you want)

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/RFID/rfid.cpp
> +  data_update_buf[0] = &((uint8_t)params[0]);//casting fun
`&` is the address-of operator. So you appear to be writing a pointer into the data buffer...

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/RFID/rfid.h
> +#define RST_PIN	9
If you're going to indent the enum values, you should at least have this line align with the next line (or don't indent any of them)

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/ServoControl/servo_control.cpp
> +    servos[param].write((value[0]);
Delete extra set of parens

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/ServoControl/servo_control.cpp
> +    data_update_buf[0] = ((uint8_t)servos[param].read()); //32 bit return, must cast to 8 bit buffer
Outer parentheses here don't do anything. Maybe you meant to put them around `servos[param].read()` instead, to clarify the scope of the cast? (FYI I would do that, since I don't recall offhand the operator precedence of the cast)

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/ServoControl/servo_control.h
> +#define LED_PIN 13 //unchanged
Why have the "unchanged" comment here? Looks like a temporary debugging thing.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/YogiBear/YogiBear.cpp
> +        int scaled255 = value * (255/100);
If you do want scaling you probably want `(value * 255) / 100`, not the current order of operations. I believe the value of `255/100` will be `2`, because these are integer operations and floats are not used as intermediaries.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/YogiBear/YogiBear.cpp
> +          // clearFault();
Delete commented out code... and, in that case, the entire `if (fault == 0)` statement can go. Leave behind a TODO if there's some unimplemented functionality here.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/YogiBear/YogiBear.cpp
> +      if ((value <= 100) && (value >= 0)) {
See my comment above re scaling.

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/YogiBear/YogiBear.cpp
> +}
Add newline at eof

2016-11-19 23:10 UTC, nikitakit commented on hibike/devices/YogiBear/YogiBear.json
> +    "deviceID": "0x0042",
Why is this file here? It looks like a remnant of old hibike.

2016-11-19 23:10 UTC, nikitakit commented on hibike/hibike_message.py
>  from __future__ import print_function
Note the change of file mode from `644` to `755`. Why???

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +                offset += status;}
put the closing brace on a new line

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +                params = params & ~(1<<count);}
Put the closing curly brace on a new line

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +          for (uint16_t count = 0; (params >> count) > 0; count++) {
You should revisit the indentation for this entire `for` loop

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_device.cpp
> +                params = params & ~(1<<count);}
The fact that you're clearing the bit looks odd here. But since the indentation is so messed up, I'll let you fix that first before I try to figure out what this code actually means.

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_message.cpp
> +//deprecated but not really
What's going on here? This comment does not inspire confidence in the code...

2016-11-19 23:10 UTC, nikitakit commented on hibike/lib/hibike/hibike_message.cpp
> +  for (uint16_t count = 0; (params >> count) > 0; count++) {
Could you compare with: https://github.com/pioneers/PieCentral/pull/81/files#diff-5d8c7794330dd1be44ef7e70483aaa9aR49 and check if there is needless duplication?

2016-11-19 23:12 UTC, yizow requested changes
Didn't review virtual devices stuff.

2016-11-19 23:12 UTC, yizow commented on hibike/ATALANTA_INTEGRATION.md
> +- callibrate: bool write only
two L's typo

2016-11-19 23:12 UTC, yizow commented on hibike/README.md
> +|         |                | 6            | callibrate | bool       | no    | yes    |
two L's typo

2016-11-19 23:12 UTC, yizow commented on hibike/__init__.py
> +from . import hibike_message
add newline

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if (param ==1 && MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t) ){
space after `==`

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >1 && param<5 && MAX_PAYLOAD_SIZE - buf_len < sizeof(float) ){
space between comparotors

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >=2 && param<){
space between comparotors

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >=2 && param<){
space between comparotors

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  if (param == 0 && MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)){
I dont know what param `0` is, and neither will anyone reading this code. Use an enum or something.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  }
do all these close brackets even compile?

2016-11-19 23:12 UTC, yizow commented on hibike/devices/BatteryBuzzer/battery_buzzer.cpp
> +  else if(param >1 && param<5 && MAX_PAYLOAD_SIZE - buf_len < sizeof(float) ){
but parenthesis around all your predicates. makes it clearer and reduces errors.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ColorSensor/color_sensor.cpp
> +  if (buf_len < sizeof(uint16_t)|| param >3|| param<0) {
clean up your if predicates. Spaces around comparators. 

Does the number `3` have semantic meaning? If so, it should be a constant variable.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/DigitalDistance10cm/digital_distance_10cm.cpp
> +	return 0;
Uhhh you just nullified the rest of this function? 

If so, delete the rest of this function.
And fix the whitespace.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/LimitSwitch/limit_switch.cpp
> +  if (MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t) || param >= NUM_SWITCHES) {
add paranthesis around all your individual predicates

style, and less easy to make mistakes.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/LimitSwitch/limit_switch.cpp
> +// uint8_t data_update(uint8_t* data_update_buf, size_t buf_len) {
delete this code, don't comment it. 

version control (i.e. git) will preserve this if you ever want to go back to it.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/LineFollower/line_follower.cpp
> +  if (MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)|| param > 2 || param < 0) {
put paranethsis around predicates. and spaces between operators.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/LineFollower/line_follower.cpp
> +// uint8_t data_update(uint8_t* data_update_buf, size_t buf_len) {
delete this code dont comment it.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/MetalDetector/metal_detector.cpp
> +  return 0;
this completely nullifies the rest of the function. either delete it or remove this line.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.cpp
> +  if (MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t) || param>2 || param<0) {
put paranethesis around your predicates.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.cpp
>  // append_buf copies the specified amount data into the dst buffer and increments the offset
what is the "dst" buffer? are these comments relevant anymore?

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define NUM_PARAMS 5
just remove this line

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define NUM_PINS 4
just remove this line

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.h
> +//#define IN_3 A3
just remove this line

2016-11-19 23:12 UTC, yizow commented on hibike/devices/Potentiometer/potentiometer.h
>  #define IN_0 A0
There is no point of these defines if you never use them in the `.cpp` file. 

If these lines need to be present in every sensor's header file, place them in a shared `devices_util.h` file or something like that

2016-11-19 23:12 UTC, yizow commented on hibike/devices/RFID/rfid.cpp
> +// you must implement this function. It is called when the device receives a DeviceUpdate packet.
are device update and device status still relevant?

2016-11-19 23:12 UTC, yizow commented on hibike/devices/RFID/rfid.cpp
> +  if(MAX_PAYLOAD_SIZE - buf_len < sizeof(uint32_t)|| param!=0){
style fixes to if statement: see above comments.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/RFID/rfid.h
> +#define SS_PIN	10
purely style change: looks better to have all the numbers lined up.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(param< NUM_PINS && len< sizeof(servos[param]) || len< sizeof(toggle0)){
clean up if statement with parentheses

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +    servos[param].write((value[0]);
SOMEONE DIDNT TEST THAT THIS CODE COMPILES.
BECAUSE THAT EXTRA PARENTHESIS WONT COMPILE.

FOR SHAME. NO TESTING.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +    // case TOGGLE2:
delete this commented out code

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(MAX_PAYLOAD_SIZE - buf_len < sizeof(uint8_t)|| param>NUM_PINS*2 || param < 0){
clean up if statement

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +  if(param<2){
add spaces around comparator

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
>  }
add newline at end of file

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.cpp
> +  else if (params == NUM_PINS+1){
style: add spaces around `+`

2016-11-19 23:12 UTC, yizow commented on hibike/devices/ServoControl/servo_control.h
> +#define LED_PIN 13 //unchanged
why is the unchanged comment neccesssary?

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.cpp
> +      return sizeof(uint8_t);
is break necessary if we have return?

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.cpp
> +      setLed(0, data[0]);
`data[0]` is used in every set function.  bind it to a local variable. 

or, use the select purely to get the first argument of `setLed`, and just have a single call to `setLed` outside the switch.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.cpp
> +      data_update_buf[0] = getLed(0);
maybe consider moving `data_update_buf[0]` to outside the cases.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.cpp
>  }
add new line

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.h
> +#define PARAM_BLUE 1
if you define an enum, you could use that in the switch code directly and safely without needing to map from `PARAM____` to a number

2016-11-19 23:12 UTC, yizow commented on hibike/devices/TeamFlag/team_flag.h
> +  1,                      // Year
Uh oh. This worries me. 
There should be a very global header file that holds global constants used by _every_ device, like the year. otherwise you'll have to modify this for every device, every year.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +// int IN_ENA = I08;
delete commented out lines.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +  // pinMode(IN_ENA, INPUT);
delete the commented out lines.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +        int scaled255 = value * (255/100);
this is integer division, right? i.e. `scaled255 = value * 2`

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +        int scaled255 = value * (255/100);
if we have access to default arduino code: 
https://www.arduino.cc/en/Reference/Map

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +        int scaled255 = value * (255/100);
Wait forget everything i said here, move it to the device_write_update function. `device_update` is deprecated.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +        int scaled255 = value * (255/100);
see above comment. use arduino map function.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.cpp
> +}
add newline at end of file.

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.h
> +  DUTY = 0,
does it matter that DUTY is explicitly 0? 

if not, these changes arent neccessary

2016-11-19 23:12 UTC, yizow commented on hibike/devices/YogiBear/YogiBear.json
> +}
add newlines to end of file.

2016-11-19 23:12 UTC, yizow commented on hibike/hibikeDevices.json
> +]
add new line at end of file

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +paramMap = {device["id"]: {param["name"]: (param["number"], param["type"], param["read"], param["write"]) for param in device["params"]} for device in devices}
this one line is so hard to read.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +     if (1 & (params_bitmask >> param_count) == 1):
`(params_bitmask & (1 << param_count))`

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +     if (1 & (params_bitmask >> param_count) == 1):
or, `converted_params = [param_count if (params_bitmask & (1 << param_count)) for param_count in range(16)]`
to combine 4 lines into 1.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +     if (1 & (params_bitmask >> param_count) == 1):
choose the one you think is more readable.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +  temp_payload = struct.pack("<HHHBQ", tot, delay, device_type, year, id_num)
I dont think this was tested. `tot` is not defined.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +  params = [param[0] for param in params_and_values]
`params, values = zip(* params_and_values)`

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +  params = [param_tuple[0] for param_tuple in params_and_values]
`params, values = zip(* params_and_values)`

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_message.py
> +def blocking_read(serial_conn):
do we include the length of the message in the bytestream we receive? 
How is this blocking? are you assuming serial_conn has a timeout on it? 

This file doesnt even import serial. The above answers should be commented here, i feel.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_process.py
> +class DeviceWriteThread(threading.Thread):
Are we going to rewrite these classes to not extend `threading.Thread`?

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_process.py
> +            packet = hm.blocking_read(self.ser)
again, i'm not too sure how this blocks.

2016-11-19 23:12 UTC, yizow commented on hibike/hibike_process.py
> +    # helper functions so we can spawn threads that try to
threads that try to...?

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +            if (params & (1<<count)){
fix if statement style

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +              if(status){
put spaces after `if` and before `{`

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +          // param = hibikeBuff.payload[0] - 1;
delete code, noneed to comment it out when we're using git version control.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +        // case DESCRIPTION_REQUEST:
Why is this one commented out, but the other ones are now commented out but have a comment `Unsupported packet`?

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
>            // Uh oh...
You could blink something here. or something for th user to see.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +  // if ((subDelay > 0) && (currTime - prevTime >= subDelay)) {
delete this code if its not being used.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.cpp
> +
unnecessary new line

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_device.h
> +//extern uint8_t device_data_update(int param, uint8_t* data_update_buf, size_t buf_len);
delete, not comment out.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +//deprecated but not really
waht ._.
pls explain

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +int send_data_update(uint16_t params) {
whitespace at end of line. remove.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +      if (params & (1<<count)){
fix if statement spacing.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +          params &= ~(1<<count);
fix spacing around `<<`

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +        if(bytes_written){
fix spacing.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +    // send_data_update(params, hibikeBuff.payload,hibikeBuff.payload_length); //what does this do?
remove this line.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.cpp
> +    return send_message(&msg); //what does this do?
is that comment "what does this do" still relevant? 
If so, i'd like it answered.

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.h
> +
so many newlines may not be neccessary

2016-11-19 23:12 UTC, yizow commented on hibike/lib/hibike/hibike_message.h
>  #endif /* HIBIKE_H */
put a newline at end of file though.

2016-11-19 23:48 UTC, nikitakit commented on hibike/spawn_virtual_devices.py
> +    lines = [str(socat.stderr.readline()), str(socat.stderr.readline())]
`str` is not the right function for converting bytestrings to strings. Try `str(b"test")` in the REPL, it won't do the right thing.

If fixing bytestrings is indeed needed, you need to use `encode` to specify ascii, utf-8, or another encoding.

Given that `str` cannot possibly cast correctly, then either:

1. You can remove the cast
2. You should use the correct byte-to-str conversion

2016-11-19 23:51 UTC, nikitakit commented on hibike/devices/ServoControl/servo_control.cpp
> +    servos[param].write((value[0]);
Oh wait, the parens are mismatched here! Does this file even compile? And if it doesn't, then has the code ever been tested on hardware?

2016-11-20 00:54 UTC, karthik-shanmugam commented
I'm considering dropping these two commits from the pr because they contain all the broken C++ code.

https://github.com/pioneers/PieCentral/pull/81/commits/3847278c9695886292a0bcabe2ea636f7c104589

https://github.com/pioneers/PieCentral/pull/81/commits/a701a50cd75b4b2b3513b3984103ff6f9c723ef3

However doing this will break the TeamFlag and YogiBear code included in a later commit (they should still compile but won't actually respond to writes)

I'm not going to actually drop these commits and rebase this branch yet because it might confuse github's code review system

2017-01-12 00:15 UTC, closed without merging