[RUNTIME] Deduplicated runtime code
pioneers/PieCentral pull request #82
Opened 2016-11-28 19:56 UTC by yizow

The main code for runtime is now deduplicated. Previously, runtime() and
runtimeTest() had 2 different copies of largely the same code. Those
lines have been merged into the new runtime() function.

This commit also fixes a few bugs that were causing tests to fail:
1. E-stop test did not actually have an output file
2. Ansible had a typo with parenthesis
3. Ansible processes are terminated in between tests to release their
port.

2016-11-29 01:24 UTC, nikitakit requested changes
This changeset LGTM, but I'd like to see a comment added about UDP termination.

However a look at the latest version of the code has brought to my attention two other comments that I think should have been brought up in earlier reviews. I would like to see these added to the github issue tracker or addressed in future commits.

2016-11-29 01:24 UTC, nikitakit commented on runtime/testy/runtime.py
> +          print("Too many restarts, terminating")
Just saw the `if emergency_stopped` condition above this print statement. At some point, you should make the printed messages match up with what's actually happening (i.e. estop is not the same as too many restarts)

2016-11-29 01:24 UTC, nikitakit commented on runtime/testy/runtime.py
> +  maxIter = 3 if testMode else 0
Again unrelated to the current changeset, but `maxIter` of 0 meaning unlimited is highly misleading. While this is standard practice in C due to the limits of the type system, for Python you may as well use `None` to make it clear that this is a signalling value.

2016-11-29 01:24 UTC, nikitakit commented on runtime/testy/runtime.py
> -      terminate_process(allProcesses[PROCESS_NAMES.STUDENT_CODE])
Wait... the old code on this line would crash really badly, right?

2016-11-29 01:24 UTC, nikitakit commented on runtime/testy/runtime.py
> +    print(e)
I trust that you know what you're doing with regards to changing the exception printing code. (TBH I don't know what the difference between the old and the new code on this line is)

2016-11-29 01:24 UTC, nikitakit commented on runtime/testy/runtime.py
> +      terminate_process(PROCESS_NAMES.UDP_SEND_PROCESS)
I think you want a comment about why these two terminate lines are here. (I can see that it's due to having multiple tests, but it took me a bit of cross-referencing other chunks of code to figure that out)

2016-12-03 01:08 UTC, yizow reviewed
Addressed changes.

2016-12-03 01:08 UTC, yizow commented on runtime/testy/runtime.py
> +  maxIter = 3 if testMode else 0
Fixed

2016-12-03 01:08 UTC, yizow commented on runtime/testy/runtime.py
> +          print("Too many restarts, terminating")
Fixed

2016-12-03 01:08 UTC, yizow commented on runtime/testy/runtime.py
> -      terminate_process(allProcesses[PROCESS_NAMES.STUDENT_CODE])
I moved the dictionary lookup into the terminate_process function. This way i can simultaenously remove a terminated process from all processes. 
Before, this code would just overwrite the old value in the dictionary when the new process is started.

2016-12-03 01:08 UTC, yizow commented on runtime/testy/runtime.py
> +    print(e)
`except` and `except Exception as e` match the same cases, but this new code also exposes the exception object.
This lets the printed trace be more descriptive.

2016-12-03 01:08 UTC, yizow commented on runtime/testy/runtime.py
> +      terminate_process(PROCESS_NAMES.UDP_SEND_PROCESS)
Fixed

2016-12-03 01:14 UTC, nikitakit requested changes
Minor style things

2016-12-03 01:14 UTC, nikitakit commented on runtime/testy/runtime.py
> +      if not testMode:
Collapse out repeated `if not testMode`

2016-12-03 01:14 UTC, nikitakit commented on runtime/testy/runtime.py
> +    while (not terminated) and (maxIter == None or execCount < maxIter):
`is None`

2016-12-03 06:30 UTC, nikitakit approved these changes

2016-12-03 06:47 UTC, merged