Dawn sagas tests
pioneers/PieCentral pull request #89
Opened 2017-01-04 16:48 UTC by kev-chien

Written 6/7 (-ish) tests for sagas in `renderer/utils/sagas.js`. 
Addresses #38 .

### Notes
- Modified `sagas.js` a bit to allow tests to run
- Added the action "SAVE_FILE_SUCCEEDED" to `actions/editorActions.js` for consistency
- electron can't be tested (remote and ipcRenderer do not exist), I suppose it is because the test environment differs and those elements don't exist until rendered
- I didn't write a test for ansibleGamepads() because it references navigator.getGamepads() but navigator is not imported, and is only available in the Chrome engine when the app is actually running. To solve this we could try using [electron-mocha](https://github.com/jprichardson/electron-mocha) to actually test in a running instance of electron (and thus fix/complete other tests).

2017-01-30 08:58 UTC, kevinmasd requested changes

2017-01-30 08:58 UTC, kevinmasd commented on dawn/renderer/utils/sagas.js
> +const editorState = (state) => ({
Probably going to get caught on the Linter. Otherwise looks fine for now; will need to test with the new changes though.

2017-01-30 20:55 UTC, kev-chien commented on dawn/renderer/utils/sagas.js
> +const editorState = (state) => ({
It passed the linter. I've added tests for the new changes.

2017-01-30 22:12 UTC, kevinmasd commented on dawn/renderer/utils/sagas.js
> +const editorState = (state) => ({
Meant post #101 . ESLint has new rules.

2017-01-31 00:09 UTC, kev-chien commented on dawn/renderer/utils/sagas.js
> +const editorState = (state) => ({
*.test.js is in `.eslintignore`. Should we remove this so tests are also linted?

2017-02-05 05:38 UTC, kevinmasd approved these changes

2017-02-05 05:38 UTC, merged