Networking/chris/devel
pioneers/PieCentral pull request #98
Opened 2017-01-16 10:52 UTC by Alramech

ignore client/server/driver files

2017-01-17 23:05 UTC, yizow commented
See comments on slack.

2017-01-18 01:07 UTC, yizow requested changes
PLS CHANGE FIXES PL0X

2017-01-18 01:07 UTC, yizow commented on networking/config.py
> +  END_GAME = "3"
newline at end of file

2017-01-18 01:07 UTC, yizow commented on networking/tentativename.py
> +import lcm
Change the file name and choose a casing

2017-01-18 01:07 UTC, yizow commented on networking/tentativename.py
> +t.start()
newline at end of file

2017-01-18 01:07 UTC, yizow commented on networking/test.py
> +outfile = open("testout.txt", "w")
I recommend adding a `.gitignore` file in this directory to apply to various temp files youre going to be generating. such as lcm stuff.

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +from config import Commands as cmd
cmd is a python default module. 
I recommend not overwriting it.

If you maintain config to only be global constants and enum stuff, etc, I would recommend 
`from config import *`

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +    self.teleop = False
`self.teleop` and `self.enabled` seem redundant.

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +  (0 = disabled, 1 = autonomous, 2 = teleop, 3 = estop)
i recommend having estop as 0, sinces it's more commonly used as an error state

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +    state = robot.enabled + robot.teleop + robot.estop*2
what the heck is this supposed to mean?

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +lc = lcm.LCM()
probably want to choose a different name than `lc`

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +  if data == cmd.START_GAME:
Consider using `elif` for these just to catch bug cases where you alias enums together.

2017-01-18 01:07 UTC, yizow commented on networking/robot.py
> +  if data == cmd.START_GAME:
Another alternative is to use a dictionary mapping from enum -> function definitions.

2017-01-18 01:07 UTC, yizow commented on networking/tentativename.py
> +from config import Commands as cmd
See above comments

2017-01-18 01:07 UTC, yizow commented on networking/tentativename.py
> +lc = lcm.LCM()
Should probably move this to outside of function definitions

2017-01-18 01:08 UTC, yizow requested changes
Gitignore.

2017-01-18 01:09 UTC, nikitakit requested changes

2017-01-18 01:09 UTC, nikitakit commented on networking/robot.py
> +    lc.publish("ROBOT_HEARTBEAT", status)
I notice you're publishing strings on LCM.

I strongly recommend that you switch to publishing using LCM types instead (or another strict encodingy system like protobuf) -- using types helps you keep your sanity when building a distributed system.

2017-01-18 01:31 UTC, nikitakit commented on networking/robot.py
> +lc = lcm.LCM()
@yizow So `lcm` is already taken (module name), and you want something short...

2017-02-18 23:36 UTC, closed without merging